### ISSUE TITLE
Syntax Error :Unexpected token

### ISSUE THREAD

**Issue by egemenozkan** [agis/mcdetect#2]
```
egemen@machine:~$ mcdetect https://google.com
/opt/node/lib/node_modules/mcdetect/bin/mcdetect.js:34
(async() => {
      ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
```

```
egemen@machine:~$ node --version
v6.2.0
```
```

egemen@machine:~$ npm --version
3.8.9

```

**Comment by agis** [comment]
As stated in the README, node 7.6.0 or later is required.

**Comment by agis** [comment]
@egemenozkan Let me know if you have further issues. Closing this for now :)
